@auth=Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJVSUQiOiI2aGlpYVRXRUxuU09rMFhiWGI0MyIsInRva2VuIjo0LCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2ODYyMTA0NDUsImV4cCI6MTY4NjIzMjA0NX0.GGF2iSG07kKHtBCkNOq40RbGbzaGG_nFT_P575G6OhaJyjWbeJdwe8R7oTopkSw91noojLFFow4qLMnaJaJlMEuAjNB8pGeegXdmtUaNpNrrqbdwy0TAeKqwpfnh_MHuXMz_z77eWqaWPBOg2Yy4MLU7txdNMwtMwQJsiHTR5nMNkucUw4KVODLRcbF0jpOw1Je2cy7pbx-VH2o0GW2r2wpsWbk81b3mRTtYya5ocq3TVp7IGRU7vmD-UZLkolgeHCoMVIXoLtUZ9kHFqidCvlKqUerOessacGaXskGStvlylhn7qYASde5hnT0Cy8JtfoYCUGqwSLnDCLOZRHZMUw


###
POST http://localhost:8000/add/admin
content-type: application/json

{
    "username": "admin01",
    "password": "123456789",
    "fullname": "admin",
    "credit": 0
}


###
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "username": "admin01",
    "password": "123456789"
}

###
POST http://localhost:8000/auth/logout
Authorization: {{auth}}
Content-Type: application/json

{
    "username": "admin01"
}

###
POST http://localhost:8000/add/lotto
Authorization: {{auth}}
content-type: application/json

{
    "name": "ดาวน์โจนส์ VIP",
    "img_flag": "jonevip.jpg",
    "open": "2023-01-19 06.00",
    "close": "2023-01-19 00.10",
    "report": "2023-01-19 00.30",
    "status": "OPEN"
}

###
DELETE http://localhost:8000/delete/lotto
Authorization: {{auth}}
content-type: application/json

{
    "id": "LKyASx2SgDOtGFioWDT3"
}

###
GET http://localhost:8000/get/lotto/all
Authorization: {{auth}}

###
POST http://localhost:8000/add/agent
Authorization: {{auth}}
content-type: application/json

{
    "username": "agent01",
    "password": "123456789",
    "fullname": "agent",
    "credit": 0
}

###
POST http://localhost:8000/add/member
Authorization: {{auth}}
content-type: application/json

{
    "username": "member1111",
    "password": "123456789",
    "fullname": "member11111111111",
    "credit": 0,
    "store_id": "3RDYTBqOjervu82IKQXm",
    "agent_create_id": "pSJ2jiwWPMj7ksCQG5wV",
    "admin_create_id": "6hiiaTWELnSOk0XbXb43",
    "manager_create_id": "9pxJRIMKeNIRhqJlMDcZ",
    "role": "MEMBER",
    "status": "REGULAR"
}

###
GET http://localhost:8000/get/bill/all
Authorization: {{auth}}

###
GET http://localhost:8000/get/user/me
Authorization: {{auth}}

###
GET http://localhost:8000/get/user/all
Authorization: {{auth}}

###
PUT http://localhost:8000/update/status/agent
Authorization: {{auth}}
content-type: application/json

{
    "id": "85MI669pD37GGckaKAxh",
    "status": "REGULAR"
}